name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://huggingface.co
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Action"
          git push --force https://Casses:$HF_TOKEN@huggingface.co/spaces/casses1122/riddle main
